TokenAmountMaster.delete_all()
TokenAmountMaster.create(token_amount_master_id: 0, token_amount: 1)
TokenAmountMaster.create(token_amount_master_id: 1, token_amount: 5)
TokenAmountMaster.create(token_amount_master_id: 2, token_amount: 10)
TokenAmountMaster.create(token_amount_master_id: 3, token_amount: 50)